run:
  binary:
    source: https://github.com/meenaravichandran1/drone-gcs/releases/download/{{ release }}/plugin-{{ os }}-{{ arch }}.zst
    fallback_source: https://app.harness.io/storage/harness-download/harness-ti/drone-gcs/{{ release }}/plugin-{{ os }}-{{ arch }}.zst