FROM arm32v6/alpine:3.12 as alpine
RUN apk add -U --no-cache ca-certificates

FROM arm32v6/alpine:3.12

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GCS" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ENV GODEBUG netdns=go
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ADD release/linux/arm/drone-gcs /bin/
ENTRYPOINT ["/bin/drone-gcs"]
