# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2019 as core

FROM mcr.microsoft.com/windows/servercore:ltsc2019 as roots
COPY docker/windows/ C:/roots-src/
RUN powershell -NoProfile -ExecutionPolicy Bypass -File C:\roots-src\export-roots.ps1


FROM plugins/base:windows-1809-amd64
USER ContainerAdministrator
SHELL ["cmd", "/S", "/C"]

ENV GODEBUG=netdns=go
COPY --from=core /windows/system32/netapi32.dll /windows/system32/netapi32.dll
COPY --from=roots /roots/ /roots/
RUN for %f in (C:\roots\*.reg) do @(reg import "%f" || exit 1)

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GCS" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-gcs.exe C:/drone-gcs.exe
ENTRYPOINT [ "C:\\drone-gcs.exe" ]