FROM alpine:3.12 as alpine
RUN apk add -U --no-cache ca-certificates

FROM alpine:3.12
ENV GODEBUG netdns=go

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GCS" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
RUN mkdir -p /tmp
RUN chmod 777 /tmp

ADD release/linux/amd64/drone-gcs /bin/
ENTRYPOINT ["/bin/drone-gcs"]
