# escape=`
FROM mcr.microsoft.com/windows/nanoserver:1803
USER ContainerAdministrator

ENV GODEBUG=netdns=go

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GCS" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-gcs.exe C:/drone-gcs.exe
ENTRYPOINT [ "C:\\drone-gcs.exe" ]